name = "hex-roots"
defaultTargets = ["HexRoots"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "10c058178b514bc6fc448ca0f8d44a1f5b3ba133"

[[lean_lib]]
name = "HexRoots"
