name = "hex-roots"
defaultTargets = ["HexRoots"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "a3d2bc38d47673cc724feb01ba277e787b313719"

[[lean_lib]]
name = "HexRoots"
