name = "hex-roots"
defaultTargets = ["HexRoots"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "6d06e29656068186a94eafc92d3325880294bb16"

[[lean_lib]]
name = "HexRoots"
